### ISSUE TITLE
[bug] ArrayIndexOutOfBoundsException of read-str

### ISSUE THREAD

**Issue by redraiment** [gerritjvv/pjson#20]
`(pjson.core/read-str "[{\"a\":\"J\\\\\"}]")` throws an ArrayIndexOutOfBoundsException

**Comment by redraiment** [comment]
`(pjson.core/write-str ["b\\"])` returns `["b\\\"]"]`

**Comment by gerritjvv** [comment]
thanks, i'll have a look and  fix

**Comment by gerritjvv** [comment]
Have a look at https://github.com/gerritjvv/pjson/pull/21 branch is issue_20_index-out-of-bounds this should solve the reading issue. 

Everything in this api is about speed, but I've decided to make a compromise and when an escape is detected before an end of String the method will drop into a slower reading method to properly read the string.

**Comment by gerritjvv** [comment]
done the same for the write-str also.
 
plz try the latest 0.3.6-SNAPSHOT and see if this fixes the escaping for you.

**Comment by redraiment** [comment]
@gerritjvv 0.3.6-SNAPSHOT works well for write-str, however, read-str still have an issue:

`(json/read-str (json/write-str [{:name "Joe\\"}]))` returns `[{"name" "Joe\\\\"}]`, which should be `[{"name" "Joe\\"}]`

**Comment by gerritjvv** [comment]
please try again, with the latest snapshot pjson/pjson/0.3.6-SNAPSHOT/pjson-0.3.6-20160930.110525-2.jar

I've fixed the writing and reading and have a test to validate

```
(deftest test-read-write-escape
  (is
    (=
      (pjson/read-str (pjson/write-str (pjson/read-str (pjson/write-str (pjson/read-str (pjson/write-str [{:name "Joe\\"}]))))))
      [{"name" "Joe\\"}])))
```

**Comment by gerritjvv** [comment]
please ignore, I've realised the build is failing :(

**Comment by gerritjvv** [comment]
ok please try now, I've uploaded the latest version, pjson now parsers at full speed and only when it finds an escape char will it move to a slower string parse method, only for those strings that contain the escape char.

pjson/pjson/0.3.6-SNAPSHOT/pjson-0.3.6-20160930.134906-3.jar

**Comment by redraiment** [comment]
It looks good! Thanks! 👍

**Comment by gerritjvv** [comment]
great to hear! I'll make a release soon.
